baseURL: ""
languageCode: en-us
title: Kanan Yusubov
theme: PaperMod

params:
  social:
  author: Kanan Yusubov
  keywords: [blog, page ]
  label:
    title: Test
    icon: /profile.jpg
  cover:
    responsiveImages: true
  profileMode:
      enabled: true
      title: "Kanan Yusubov" # optional default will be site title
      subtitle: "Senior Mobile Platforms Engineer (Flutter) & Founder of Azerbaijan Flutter Users Community"
      imageUrl: "profile.jpeg" # optional
      imageTitle: "<title of image as alt>" # optional
      imageWidth: 200 # custom size
      imageHeight: 200 # custom size
      buttons:
        - name: Archive
          url: "/archives"
        - name: Tags
          url: "/tags"
        - name: My Resume
          url: "/docs/Resume.pdf"
  socialIcons:
    - name: "email"
      url: ""
    - name: "dev@yusubov.com"
      url: "https://www.linkedin.com/in/thisisyusub/"
    - name: "facebook"
      url: "https://www.facebook.com/kanan.yusub"
    - name: "github"
      url: "https://github.com/thisisyusub"
    - name: "medium"
      url: "https://medium.com/@thisisyusub"
    - name: "spotify"
      url: "https://open.spotify.com/user/31cfyo6olr4agp2lqgcv6mrnoyja?si=84f7a7a40721495f"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/10996870/thisisyusub"
    - name: "telegram"
      url: "https://t.me/yusubX"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UC9j42eR0UxQTwKHY_j71i4g" 
  linkFullImages: true
  showReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowWordCount: true
  hideFooter: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 2
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 3
    - identifier: video-tutorials
      name: Video Tutorials
      url: /video-tutorials/
      weight: 4
    - identifier: notes
      name: Notes
      url: /notes/
    - identifier: conference-talks
      name: Conference Talks
      url: /conference-talks/

