baseURL: "https://yusubov.com/"
languageCode: en-us
title: Thisisyusub
theme: PaperMod
enableRobotsTXT: true
disqusShortname: yourDisqusShortname

params:
  keywords: [blog, page ]
  label:
    title: Test
    icon: /profile.jpg
  cover:
    responsiveImages: true
  comments: true
  profileMode:
      enabled: true
      subtitle: " Flutter Enthusiast (3+ years) & Founder of Azerbaijan Flutter Users Community"
      imageUrl: "profile.jpeg" # optional
      imageTitle: "<title of image as alt>" # optional
      imageWidth: 200 # custom size
      imageHeight: 200 # custom size
      buttons:
        - name: Archive
          url: "/archives"
        - name: Tags
          url: "/tags"
        - name: My Resume
          url: "/docs/Resume.pdf"
  socialIcons:
    - name: "rss"
      url: "https://yusubov.com/index.xml"
    - name: "email"
      url: "dev@yusubov.com"
    - name: "linkedin"
      url: "https://www.linkedin.com/in/thisisyusub/"
    - name: "facebook"
      url: "https://www.facebook.com/kanan.yusub"
    - name: "github"
      url: "https://github.com/thisisyusub"
    - name: "medium"
      url: "https://medium.com/@thisisyusub"
    - name: "spotify"
      url: "https://open.spotify.com/user/31cfyo6olr4agp2lqgcv6mrnoyja?si=84f7a7a40721495f"
    - name: "stackoverflow"
      url: "https://stackoverflow.com/users/10996870/thisisyusub"
    - name: "telegram"
      url: "https://t.me/yusubX"
    - name: "youtube"
      url: "https://www.youtube.com/channel/UC9j42eR0UxQTwKHY_j71i4g" 
  homeInfoParams:
        Title: Hi there!
        Content: Can be Info, links, about...
  linkFullImages: true
  showReadingTime: true
  ShowCodeCopyButtons: true
  ShowPostNavLinks: true
  ShowWordCount: true
  ShowFullTextinRSS: true
  hideFooter: true
  # for search
  # https://fusejs.io/api/options.html
  fuseOpts:
    isCaseSensitive: false
    shouldSort: true
    location: 0
    distance: 1000
    threshold: 0.4
    minMatchCharLength: 0
    keys: ["blog", "notes", "portfolio", "about"]
  outputs:
  home:
    - HTML
    - RSS
    - JSON # is necessary
  ShowToc: true

menu:
  main:
    - identifier: about
      name: About
      url: /about/
      weight: 1
    - identifier: portfolio
      name: Portfolio
      url: /portfolio/
      weight: 2
    - identifier: blog
      name: Blog
      url: /blog/
      weight: 3
    - identifier: videos
      name: Video Tutorials
      url: /video-tutorials/
      weight: 4
    - identifier: notes
      name: Notes
      url: /notes/
    - identifier: conferences
      name: Conference Talks
      url: /conference-talks/
    - identifier: search
      name: Search
      url: /search/

